version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.1.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.1.0
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./ChromeForTesting:/usr/bin/chromedriver
    shm_size: 2gb

  xvfb:
    image: selenium/standalone-chrome:4.1.0
    container_name: xvfb
    environment:
      - DISPLAY=:99
    volumes:
      - ./ChromeForTesting:/usr/bin/chromedriver
    shm_size: 2gb

  robot:
    image: python:3.9-slim
    container_name: robot
    depends_on:
      - selenium-hub
      - xvfb
    volumes:
      - .:/project
    working_dir: /project
    environment:
      - DISPLAY=:99
    command: >
      sh -c "apt-get update &&
             apt-get install -y xvfb &&
             pip install robotframework robotframework-seleniumlibrary &&
             Xvfb :99 -screen 0 1920x1080x24 &
             robot input_tests/"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=
    depends_on:
      - robot

volumes:
  jenkins_home: